name: Metrics Terminal
on:
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
jobs:
  metrics-terminal:
    runs-on: ubuntu-latest
    steps:
    
    - name: Example
      uses: lowlighter/metrics@latest
      with:
        template: terminal
        filename: metrics.terminal.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: header, metadata
